# Names: Shenghua Jin, Luke Choi
# SFU IDs: 301659564, 301658198
# Emails: sja204@sfu.ca, esc9@sfu.ca
#
# Statement of Originality:
# All the code and comments below are my (our) own original work. For any non-
# original work, I (we) have provided citations above and in the comments with
# enough detail so that someone can see the exact source and extent of the
# borrowed work.
#
# In addition, I (we) have not shared this work with anyone else, and I (we) have
# not seen solutions from other students, tutors, websites, books, etc.

import csv
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

# This script trains a simple Feed-Forward Neural Network 
# using PyTorch on the dataset generated by the C++ Minimax agent.

def load_data(filename="dataset.csv"):
    inputs = []
    labels = []
    try:
        with open(filename, 'r') as f:
            reader = csv.reader(f)
            header = next(reader) # skip header
            for row in reader:
                # First 44 values are inputs (42 board cells + 2 anvil booleans)
                # Last value is the best move (0-13)
                if len(row) < 45: continue
                
                inputs.append([float(x) for x in row[:-1]])
                labels.append(int(row[-1]))
    except FileNotFoundError:
        print(f"Error: {filename} not found. Please run the C++ data generator first.")
        return None, None
        
    return torch.tensor(inputs, dtype=torch.float32), torch.tensor(labels, dtype=torch.long)

class Connect4NN(nn.Module):
    def __init__(self):
        super(Connect4NN, self).__init__()
        # Input: 44 features
        # Hidden: 64 nodes (can be tuned later)
        # Hidden: 64 nodes
        # Output: 14 possible moves
        self.fc1 = nn.Linear(44, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 14)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

def train_model(epochs=50, batch_size=64, lr=0.01):
    X, y = load_data("dataset.csv")
    if X is None: return
    
    print(f"Loaded {len(X)} training samples.")
    
    dataset = TensorDataset(X, y)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    
    model = Connect4NN()
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    
    for epoch in range(epochs):
        total_loss = 0
        for batch_X, batch_y in dataloader:
            optimizer.zero_grad()
            outputs = model(batch_X)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            
        print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss/len(dataloader):.4f}")
        
    print("Training complete!")
    return model

def export_weights(model, filename="weights.txt"):
    # To use our model in our simple C++ engine without heavy dependencies,
    # we export the trained weights and biases to a simple text file.
    with open(filename, 'w') as f:
        for name, param in model.named_parameters():
            f.write(f"--- {name} ---\n")
            # Flatten the tensor to a 1D array of strings
            flat_data = param.data.flatten().tolist()
            f.write(' '.join([str(val) for val in flat_data]) + "\n")
    print(f"Exported weights to {filename}")

if __name__ == "__main__":
    print("Starting Model Training...")
    model = train_model(epochs=100) # 100 epochs for better learning
    if model:
        export_weights(model, "weights.txt")
